# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "fpla-tfstate-bucket"
    key     = "global/loadtest/start_stop/terraform.tfstate"
    profile = "foul-play"
    region  = "us-east-1"
  }
}
