# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  profile                 = "foul-play"
  region                  = "us-east-1"
  default_tags {
   tags = {
     Terraform   = "true"
    }
  }
}
